### ISSUE TITLE
Does the training data in the paper differ from the provided models on Github?

### ISSUE THREAD

**Issue by TGabor** [marl/crepe#39]
Hi,

thanks for sharing your work! 🚀 

I'm a bit confused which dataset and instruments were actually used for the provided models on Github.
 
In the paper, only **RWC-synth** and
**MDB-stem-synth** are specified as datasets. In the conclusions, a training on NSynth is mentioned for future work

In the README on Github:
```
The provided model is trained using the following datasets, composed of vocal and instrumental audio, and is therefore expected to work best on this type of audio signals.
* MIR-1K [1]
* Bach10 [2]
* RWC-Synth [3]
* MedleyDB [4]
* MDB-STEM-Synth [5]
* NSynth [6]
```
How did you determine the ground-truth f0 for the datasets that have only an annotated midi pitch, e.g. NSynth?

**Comment by jongwook** [comment]
You are correct; in the paper I used the two datasets (RWC-synth and MDB-stem-synth), and for the Python package I used the mixture of the 6 datasets.

The reasoning behind this is that for the paper I needed an objective experimental setup based on a certain dataset, so that I can compare easily and fairly with other methods and analyze the results. On the other hand, for the Python package I wanted the model to generalize to diverse sources of audio, so I trained on whatever datasets annotated with monophonic F0 that I could get my hands on.

NSynth contains the midi number, and I assumed that it uses A440 tuning.

**Comment by TGabor** [comment]
Did you restrict the training in a certain way, e.g. only using the training split of NSynth or leaving out certain instruments or did you use the entire datasets in your training?

Did you evaluate the Github models again with the same procedure as described in the paper to check if their performance is not degraded by less accurate F0s from the additional datasets?

**Comment by jongwook** [comment]
> Did you restrict the training in a certain way, e.g. only using the training split of NSynth or leaving out certain instruments or did you use the entire datasets in your training?

AFAIR I used all splits. Again, the purpose is to gather as diverse datasets as possible, than to follow the standard procedure to produce objective evaluation.

> Did you evaluate the Github models again with the same procedure as described in the paper to check if their performance is not degraded by less accurate F0s from the additional datasets?

Not in a comprehensive way. I wouldn't be surprised if the "fits-all" model performes less than the specialized ones.
