### ISSUE TITLE
when pitch is 0?

### ISSUE THREAD

**Issue by RichardoMrMu** [marl/crepe#47]
When the pitch in audio is zero, the ouput is the most likely pitch but not zero. Why the model do not take silence into consideration?

**Comment by jongwook** [comment]
First of all, we shouldn't say the pitch is zero in silence because that doesn't make sense physically, although some datasets may use zero to annotate silence, for convenience/conciseness reasons.

Pitch tracking is actually composed of voice activity detection (VAD) and pitch estimation, and CREPE is only optimized and evaluated for the latter.

You can perform VAD by simple energy thresholding provided that the audio is clean enough, and CREPE's confidence output can be a good heuristic indicating voice activity/inactivity. If you need a more robust VAD, it is an active research area. [See this](https://arxiv.org/pdf/1903.02844.pdf) for a resent survey of methods.
