### ISSUE TITLE
imshow is deprecated, replace with matplotlib

### ISSUE THREAD

**Issue by justinsalamon** [marl/crepe#5]
imshow is [deprecated](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imsave.html), we should use matplotlib for saving the figure to disk (we're already importing it, so might as well).

An aside is that I don't know if it's a good idea to make matplotlib a dependency... it's a pretty huge lib.

**Comment by jongwook** [comment]
using `maplotlib` for pitch-perfect drawing was a little pain, dealing with `dpi` and `figimage()` because with `pyplot.imshow` it's even more difficult to deal with the margins.

I don't see using deprecated `scipy.misc.imsave` as an immediate problem, as long as we freeze the dependency. If it bugs you, I'd prefer using `imageio` as suggested by the doc, rather than `pyplot`.

`matplotlib` dependency is also not a huge problem as most of our audience would have it installed anyway, but it bugs me a little bit in the pure software engineering perspective, because the only thing that we're using is the `inferno` colormap. Those are linear colormaps and can be reimplemented with < 10 lines of code.

**Comment by justinsalamon** [comment]
I think we should definitely avoid using deprecated modules in a new release, especially since it's been deprecated since 1.0.0.

I don't see the point of importing both matplotlib AND imageio, we should just use one. I'm not sure I follow what you mean by "pitch perfect drawing"? Anyway, I'm happy for us to switch to imageio if you prefer... we just need to decide.

**Comment by jongwook** [comment]
I meant to type pixel-perfect.. but anyway, let's do `imageio` for saving images, and we can save grayscale images instead of inferno for the time being.

**Comment by justinsalamon** [comment]
Replaced scipy.misc.imsave with imageio.imwrite in 592e493e60b00bdda9c59faef08b371ec4a7d61b
